name: Main Workflow

on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

jobs:
  macOS:
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@master
      - name: Get Swift Version
        run: swift -version
      - name: Resolve dependencies
        run: swift package resolve
      - name: Build
        run: swift build --build-tests
      - name: Run Test
        run: swift test --enable-code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
  linux:
    runs-on: ubuntu-20.04
    container: swift:nightly-focal
    steps:
      - uses: actions/checkout@master
      - name: Get Swift Version
        run: swift -version
      - name: Resolve dependencies
        run: swift package resolve
      - name: Build
        run: swift build --build-tests --enable-test-discovery
      - name: Run Test
        run: swift test --enable-test-discovery --enable-code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
