name: Main Workflow

on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0