name: Main Workflow

on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
      - name: actions/checkout@master
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_13.1.app; swift -version
      - name: Resolve dependencies
        run: swift package resolve
      - name: Build
        run: swift build --build-tests
      - name: Run Test
        run: swift test --enable-code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
  linux:
    runs-on: ubuntu-20.04
    container: swift:5.5
    steps:
      - name: actions/checkout@master
      - name: Get Swift Version
        run: swift -version
      - name: Resolve dependencies
        run: swift package resolve
      - name: Build
        run: swift build --build-tests --enable-test-discovery
      - name: Run Test
        run: swift test --enable-test-discovery --enable-code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0